name: 170
displayName: Box plot
fullyQualifiedName: sample_superset.170
description: ""
chartType: Bar
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20170%7D
owners: []
tags: []
service:
  id: fe37a140-5846-4b48-930c-ffa99a20338b
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: certification
      oldValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Manual\",\"state\":\"Confirmed\"},\"appliedDate\":1770382181848,\"\
        expiryDate\":1772974181848}"
      newValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Automated\",\"state\":\"Confirmed\"},\"appliedDate\":1770382185678,\"\
        expiryDate\":1772974185678}"
  fieldsDeleted: []
  previousVersion: 0.4
  changeSummary: {}
domains: []
dataProducts: []
certification:
  tagLabel:
    tagFQN: Certification.Silver
    name: Silver
    description: Silver certified Data Asset.
    style:
      color: "#ADADAD"
      iconURL: SilverCertification.svg
    source: Classification
    labelType: Manual
    state: Confirmed
  appliedDate: 1770382185699
  expiryDate: 1772974185699
dashboards:
  - id: 266b9843-2134-41c1-9f6e-7d535f29bf8a
    type: dashboard
    name: 11
    fullyQualifiedName: sample_superset.11
    description: ""
    displayName: FCC New Coder Survey 2018
    deleted: false
  - id: 5ed24c04-300e-40e0-a221-edb00c026cce
    type: dashboard
    name: 34
    fullyQualifiedName: sample_superset.34
    description: ""
    displayName: Unicode Test
    deleted: false
  - id: 85c585d7-2b99-4aaa-987a-7fdbec34494d
    type: dashboard
    name: 8
    fullyQualifiedName: sample_superset.8
    description: ""
    displayName: Orders dashboard
    deleted: false
entityStatus: Unprocessed
