name: 161
displayName: Birth in France by department in 2016
fullyQualifiedName: sample_superset.161
description: ""
chartType: Other
sourceUrl: http://localhost:8088/superset/explore/?form_data=%7B%22slice_id%22%3A%20161%7D
owners: []
tags: []
service:
  id: fe37a140-5846-4b48-930c-ffa99a20338b
  type: dashboardService
  name: sample_superset
  fullyQualifiedName: sample_superset
  displayName: sample_superset
  deleted: false
serviceType: Superset
incrementalChangeDescription:
  fieldsAdded: []
  fieldsUpdated:
    - name: certification
      oldValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Manual\",\"state\":\"Confirmed\"},\"appliedDate\":1770382181639,\"\
        expiryDate\":1772974181639}"
      newValue: "{\"tagLabel\":{\"tagFQN\":\"Certification.Silver\",\"name\":\"Silver\"\
        ,\"description\":\"Silver certified Data Asset.\",\"style\":{\"color\":\"\
        #ADADAD\",\"iconURL\":\"SilverCertification.svg\"},\"source\":\"Classification\"\
        ,\"labelType\":\"Automated\",\"state\":\"Confirmed\"},\"appliedDate\":1770382185492,\"\
        expiryDate\":1772974185492}"
  fieldsDeleted: []
  previousVersion: 0.4
  changeSummary: {}
domains: []
dataProducts: []
certification:
  tagLabel:
    tagFQN: Certification.Silver
    name: Silver
    description: Silver certified Data Asset.
    style:
      color: "#ADADAD"
      iconURL: SilverCertification.svg
    source: Classification
    labelType: Manual
    state: Confirmed
  appliedDate: 1770382185515
  expiryDate: 1772974185515
dashboards:
  - id: 5ed24c04-300e-40e0-a221-edb00c026cce
    type: dashboard
    name: 34
    fullyQualifiedName: sample_superset.34
    description: ""
    displayName: Unicode Test
    deleted: false
entityStatus: Unprocessed
